service: cloudformation-scheduled-tasks
plugins:
  - serverless-sam
provider:
  name: aws
  runtime: nodejs10.x
  environment:
    TASKS_TABLE:
      Ref: tasksTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        Ref: DestinationArns
    - Effect: Allow
      Action:
        - dynamodb:UpdateItem
        - dynamodb:Query
        - dynamodb:DeleteItem
      Resource:
        Ref: tasksTable
functions:
  ingest:
    handler: src/ingest.handler
    events:
      - sns:
          arn:
            Ref: ingestTopic
  schedule:
    handler: src/schedule.handler
    events:
      - schedule:
          rate:
            Ref: PollingSchedule
resources:
  Resources:
    ingestTopic:
      Type: AWS::SNS::Topic
      Properties: {}
    tasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        KeySchema:
          - AttributeName: taskId
            KeyType: HASH
          - AttributeName: executeTime
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: taskId
            AttributeType: 'S'
          - AttributeName: executeTime
            AttributeType: 'N'
        ProvisionedThroughput:
          ReadCapacityUnits:
            Ref: ReadCapacityUnits
          WriteCapacityUnits:
            Ref: WriteCapacityUnits
  Parameters:
    PollingSchedule:
      Default: rate(5 minutes)
      Type: String
      Description: The CloudWatch ScheduleExpression defining the interval the polling Lambda runs at.
    ReadCapacityUnits:
      Default: 1
      Type: Number
      Description: The read capacity units for the Scheduled Tasks DynamoDB table.
    WriteCapacityUnits:
      Default: 1
      Type: Number
      Description: The write capacity units for the Scheduled Tasks DynamoDB table.
    DestinationArns:
      Default: ''
      Type: CommaDelimitedList
      Description: A comma-separated list of possible destination SNS topic ARNs for permissioning the polling Lambda.
  Outputs:
    IngestSNSTopicArn:
      Description: The ARN of the Ingest SNS topic
      Value:
        Ref: ingestTopic
